#!/bin/bash
mkfifo raw_data.fifo
source=$1

ffmpeg -i "$source"  -vcodec rawvideo -f rawvideo -pix_fmt rgb24 -y ./raw_data.fifo &

./converter `./video_size.py "$source"` raw_data.fifo

rm raw_data.fifo

echo "Converted data created"
